"""Cover Letter Generator.

Generates personalized cover letters based on user profile, job description,
and tailoring plan with word count targeting and evidence integration.
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING

from pydantic import BaseModel, Field

from src.tailoring.config import TailoringConfig, get_tailoring_config
from src.tailoring.llm import TailoringLLM
from src.tailoring.models import CoverLetter

if TYPE_CHECKING:
    from src.extractor.models import JobDescription
    from src.scoring.models import UserProfile
    from src.tailoring.models import TailoringPlan

logger = logging.getLogger(__name__)


class CoverLetterLLMResponse(BaseModel):
    """LLM response structure for cover letter generation."""

    opening: str = Field(..., description="Opening paragraph with hook")
    body: str = Field(..., description="Body with qualifications and evidence")
    closing: str = Field(..., description="Closing with call to action")
    key_qualifications: list[str] = Field(
        default_factory=list, description="Key qualifications highlighted"
    )


COVER_LETTER_SYSTEM_PROMPT = """You are an expert cover letter writer. Your job is to create a compelling, personalized cover letter for a job application.

STRUCTURE:
1. **Opening** (1 paragraph): Hook that mentions the specific role and company, shows enthusiasm
2. **Body** (2-3 paragraphs): Top 2-3 qualifications with concrete evidence, map accomplishments to job requirements
3. **Closing** (1 paragraph): Express enthusiasm, call to action, professional sign-off

CRITICAL RULES:
- NEVER fabricate experience, skills, or accomplishments
- Only reference actual experience from the candidate's profile
- Keep specific metrics and facts exactly as provided
- Personalize for the specific company and role
- Maintain professional but authentic tone
- Target word count of {min_words}-{max_words} words (MUST be within range; aim for ~1 page by staying closer to {min_words} when possible)
- Avoid repetition: do NOT restate the opening hook in the body, and avoid repeating the role/company name in every paragraph

WRITING TIPS:
- Lead with your strongest, most relevant qualification
- Use specific numbers and achievements (from profile only)
- Show you understand the company's needs
- Connect your experience directly to job requirements
- End with confidence but not arrogance
"""


class CoverLetterService:
    """Service for generating cover letters.

    Creates personalized cover letters with proper structure,
    word count targeting, and evidence integration.
    """

    def __init__(self, config: TailoringConfig | None = None):
        """Initialize the cover letter service.

        Args:
            config: Optional TailoringConfig. Uses global config if not provided.
        """
        self.config = config or get_tailoring_config()
        self.llm = TailoringLLM(config=self.config)

    async def generate_cover_letter(
        self,
        profile: UserProfile,
        job: JobDescription,
        plan: TailoringPlan,
    ) -> CoverLetter:
        """Generate a cover letter for a job application.

        Args:
            profile: User's profile with skills and experience.
            job: Job description to tailor for.
            plan: Tailoring plan with evidence mappings.

        Returns:
            CoverLetter ready for rendering.
        """
        logger.info(f"Generating cover letter for {job.company} - {job.role_title}")

        # Generate the cover letter using LLM
        cover = await self._generate_cover_letter_with_llm(profile, job, plan)

        logger.info(
            f"Generated cover letter with {cover.word_count} words, "
            f"{len(cover.key_qualifications)} key qualifications"
        )

        return cover

    async def _generate_cover_letter_with_llm(
        self,
        profile: UserProfile,
        job: JobDescription,
        plan: TailoringPlan,
    ) -> CoverLetter:
        """Generate the cover letter using LLM.

        Args:
            profile: User's profile.
            job: Job description.
            plan: Tailoring plan.

        Returns:
            CoverLetter generated by LLM.
        """
        min_words = self.config.cover_letter_min_words
        max_words = self.config.cover_letter_max_words
        base_prompt = self._build_prompt(profile, job, plan)
        system_prompt = COVER_LETTER_SYSTEM_PROMPT.format(
            min_words=min_words,
            max_words=max_words,
        )

        prompt = base_prompt
        response: CoverLetterLLMResponse | None = None
        full_text = ""
        word_count = 0

        # We enforce the configured word-count range with one revision pass.
        for _attempt in range(2):
            response = await self.llm.generate_structured(
                prompt=prompt,
                output_model=CoverLetterLLMResponse,
                system_prompt=system_prompt,
            )

            full_text = f"{response.opening}\n\n{response.body}\n\n{response.closing}"
            word_count = len(full_text.split())

            if min_words <= word_count <= max_words:
                break

            prompt = f"""{base_prompt}

---

# REVISION REQUEST

The draft below is **{word_count} words**. Rewrite it to be **{min_words}-{max_words} words**.

Rules:
- Keep the same facts and evidence. Do not add new claims.
- Keep the same role/company and overall tone.
- Do not repeat the opening hook in the body.
- Preserve structure: opening (1 paragraph), body (2-3 paragraphs), closing (1 paragraph).

## Draft (for revision)

### Opening
{response.opening}

### Body
{response.body}

### Closing
{response.closing}
"""

        if response is None:
            raise RuntimeError("Cover letter generation failed unexpectedly.")

        return CoverLetter(
            opening=response.opening,
            body=response.body,
            closing=response.closing,
            full_text=full_text,
            word_count=word_count,
            target_job_url=job.job_url,
            target_company=job.company,
            target_role=job.role_title,
            key_qualifications=response.key_qualifications,
        )

    def _build_prompt(
        self,
        profile: UserProfile,
        job: JobDescription,
        plan: TailoringPlan,
    ) -> str:
        """Build the prompt for cover letter generation.

        Args:
            profile: User's profile.
            job: Job description.
            plan: Tailoring plan.

        Returns:
            Formatted prompt string.
        """
        # Format work history highlights
        work_highlights = ""
        for exp in profile.work_history[:3]:  # Top 3 roles
            end = exp.end_date or "Present"
            work_highlights += f"""
### {exp.title} at {exp.company} ({exp.start_date} - {end})
{exp.description}
"""

        # Format evidence mappings from plan
        evidence_text = ""
        for mapping in plan.evidence_mappings[:5]:
            evidence_text += f"- Job needs: {mapping.requirement}\n  Your evidence: {mapping.evidence}\n"

        # Format job requirements
        responsibilities = "\n".join(f"- {r}" for r in job.responsibilities[:5])
        required_skills = (
            ", ".join(job.required_skills) if job.required_skills else "Not specified"
        )

        prompt = f"""# TARGET JOB

**Company:** {job.company}
**Role:** {job.role_title}
**Location:** {job.location or "Not specified"}

## About the Role
{job.description or "Not provided"}

## Key Responsibilities
{responsibilities or "Not specified"}

## Required Skills
{required_skills}

---

# CANDIDATE PROFILE

**Name:** {profile.name}
**Current Title:** {profile.current_title}
**Years of Experience:** {profile.years_of_experience}

## Professional Summary
{profile.summary}

## Relevant Experience
{work_highlights}

## Key Skills
{", ".join(profile.skills[:15])}

---

# EVIDENCE MAPPING (from tailoring plan)

{evidence_text or "Use the strongest matches from the candidate profile."}

---

# INSTRUCTIONS

Write a compelling cover letter for {profile.name} applying to the {job.role_title} position at {job.company}.

Requirements:
1. Opening paragraph: Express enthusiasm for this specific role at {job.company}
2. Body (2-3 paragraphs): Highlight top 2-3 qualifications with concrete evidence from the profile
3. Closing paragraph: Express eagerness to discuss further, professional sign-off

Target word count: {self.config.cover_letter_min_words}-{self.config.cover_letter_max_words} words

Remember:
- ONLY use information from the candidate's actual profile
- DO NOT invent new experiences or achievements
- Keep specific metrics exactly as provided
- Make it personal to {job.company} - not a generic letter
"""
        return prompt
