from __future__ import annotations

import pytest

_SCORING_ENV_KEYS = [
    "SCORING_PROFILE_PATH",
    "SCORING_FIT_SCORE_THRESHOLD",
    "SCORING_REVIEW_MARGIN",
    "SCORING_WEIGHT_MUST_HAVE",
    "SCORING_WEIGHT_PREFERRED",
    "SCORING_WEIGHT_EXPERIENCE",
    "SCORING_WEIGHT_EDUCATION",
    "SCORING_SKILL_FUZZY_MATCH",
    "SCORING_SKILL_FUZZY_THRESHOLD",
    "SCORING_EXPERIENCE_TOLERANCE_YEARS",
    "SCORING_LOCATION_STRICT",
    "SCORING_VISA_STRICT",
    "SCORING_SALARY_STRICT",
    "SCORING_SCORING_MODE",
    "SCORING_LLM_PROVIDER",
    "SCORING_LLM_MODEL",
    "SCORING_LLM_API_KEY",
    "SCORING_LLM_BASE_URL",
    "SCORING_LLM_TIMEOUT",
    "SCORING_LLM_MAX_RETRIES",
    "SCORING_LLM_REASONING_EFFORT",
]


@pytest.fixture(autouse=True)
def _clear_scoring_env(monkeypatch):
    for key in _SCORING_ENV_KEYS:
        monkeypatch.delenv(key, raising=False)
